version: "3"

services:
  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/client
      - ./client/package.json:/client/package.json
    working_dir: /client 
    environment:
      - API_URL=http://localhost:8081/
    command: /bin/sh -c "npm start"

  server:
    build: ./server
    ports:
      - 8081:8081
    volumes:
      - ./server:/server
      - ./server/package.json:/server/package.json      
    working_dir: /server  
    depends_on: 
      - server-database
    environment:
      - DATABASE_URL=server-database:27017
    command: /bin/sh -c "npm start"
    
  server-database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/server/db

    