version: "3"

services:
  client:
    image: client:${CLIENT_TAG:-latest}
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8082:8080
    volumes:
      - ./client:/client
    working_dir: /client
    environment:
      - API_URL=http://localhost:8081/
    command: /bin/sh -c "npm start"

  server:
    image: server:${BACKEND_TAG:-latest}
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./server:/server
    working_dir: /server
    depends_on: 
      - server-database
    environment:
      - DATABASE_URL=server-database:27017
    command: /bin/sh -c "npm start"

  server-database:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./db:/server/db

