version: 2
jobs:
  build:  
    # working_directory: ~/app
    docker:
      - image: circleci/node:latest
    steps:
      # Use the checkout step to check out source code. Because working_directory is unspecified, the application is checked out to ~/project
      - run: sudo chmod -R 777 /tmp/
      - checkout
      # Use the setup_remote_docker step to create a remote Docker environment. This is required to build the Docker image for deployment
      - setup_remote_docker
      # - run:
      #       name: 'change permission'
      #       command: |
      #         set -x
      #         chmod -R 777 ~/app
      - run:
          name: 'Run docker-compose build'
          command: |
            set -x
            sudo docker-compose build --no-cache               
      - run:
          name: 'Run docker-compose'
          command: |
            set -x
            sudo docker-compose up
